### ISSUE TITLE
Síntesis de Calidad

### ISSUE THREAD

**Issue by Rigoberto2001** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-Rigoberto2001#1]
[Síntesis Gestión de Calidad de Software.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-Rigoberto2001/files/9576726/Sintesis.Gestion.de.Calidad.de.Software.pdf)

**Comment by Rosa218** [comment]
20%

**Comment by josealfredo79** [comment]
Por favor de completar este trabajo, porque no habla de gestion de calidad

**Comment by Rigoberto2001** [comment]
[SINTESIS_CORREGIDO.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-Rigoberto2001/files/9699973/SINTESIS_CORREGIDO.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado
